name: tourify
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  table_calendar: ^3.0.9
  logger: ^2.0.0
  provider: ^6.0.0
  shimmer: ^3.0.0
  curved_navigation_bar: ^1.0.6
  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/leatherbag.jpg
    - assets/images/A loose fitting dress with wide sleeves.jpg
    - assets/images/A small Sphinx statue inspired by Pharaonic civilization.jpg
    - assets/images/A stylish keychain featuring the Eye of Horus..jpg
    - assets/images/canvas bags.jpg
    - assets/images/Egyptian inspired curtains.jpg
    - assets/images/Elegant gold earrings.jpg
    - assets/images/Gold bracelet with Egyptian engravings.jpg
    - assets/images/gold bracelet with Egyptian motifs.jpg
    - assets/images/Gold necklace with Tutankhamun head.jpg
    - assets/images/Luxury pharaonic necklace.jpg
    - assets/images/Mug with pharaonic design.jpg
    - assets/images/Necklaces golden pharaonic.jpg
    - assets/images/Pharaonic ceramic mug.jpg
    - assets/images/pharaonic design t-shirts.jpg
    - assets/images/pharaonic dress.jpg
    - assets/images/Pharaonic gold bracelet.jpg
    - assets/images/Pharaonic hand pouch.jpg
    - assets/images/Pharaonic Pillows.jpg
    - assets/images/Pharaonic tote bag.jpg
